### PR TITLE
Added rubocop config for Style/WordArray and Style/RegexpLiteral

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by cornelius** [comment]
The `StyleGuide` items need to point to the file in the master branch.

**Comment by tboerger** [comment]
@cornelius damn copy and paste. Now it's updated.

**Comment by cornelius** [comment]
Cool, thanks.

**Comment by rsalevsky** [comment]
LGTM

**Comment by mssola** [comment]
LGTM

**Pull request merged**
